//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaksimShimshon.BneiMikra.App.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaksimShimshon.BneiMikra.App.Shared.Resources.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consensus.
        /// </summary>
        public static string ArticleCategoryConsensus {
            get {
                return ResourceManager.GetString("ArticleCategoryConsensus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Karaite interpretations, halakhic development, and ancient commentaries..
        /// </summary>
        public static string ArticleCategoryConsensusDescription {
            get {
                return ResourceManager.GetString("ArticleCategoryConsensusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essays.
        /// </summary>
        public static string ArticleCategoryEssays {
            get {
                return ResourceManager.GetString("ArticleCategoryEssays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal studies, interpretations, and Scriptural research from a Karaite lens..
        /// </summary>
        public static string ArticleCategoryEssaysDescription {
            get {
                return ResourceManager.GetString("ArticleCategoryEssaysDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string ArticleCategoryHistory {
            get {
                return ResourceManager.GetString("ArticleCategoryHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration of religious origins, movements, and influential figures..
        /// </summary>
        public static string ArticleCategoryHistoryDescription {
            get {
                return ResourceManager.GetString("ArticleCategoryHistoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string ArticleCategoryNews {
            get {
                return ResourceManager.GetString("ArticleCategoryNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current events, religious perspectives on global issues, and updates..
        /// </summary>
        public static string ArticleCategoryNewsDescription {
            get {
                return ResourceManager.GetString("ArticleCategoryNewsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripture.
        /// </summary>
        public static string ArticleCategoryScripture {
            get {
                return ResourceManager.GetString("ArticleCategoryScripture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles exploring sacred texts and interpretations..
        /// </summary>
        public static string ArticleCategoryScriptureDescription {
            get {
                return ResourceManager.GetString("ArticleCategoryScriptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stories.
        /// </summary>
        public static string ArticleCategoryStories {
            get {
                return ResourceManager.GetString("ArticleCategoryStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life stories, interviews, and experiences of Karaites jews..
        /// </summary>
        public static string ArticleCategoryStoriesDescription {
            get {
                return ResourceManager.GetString("ArticleCategoryStoriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written by {0}..
        /// </summary>
        public static string ArticleWrittenBy {
            get {
                return ResourceManager.GetString("ArticleWrittenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient permissions to perform this request..
        /// </summary>
        public static string HttpStatusCodeForbidden {
            get {
                return ResourceManager.GetString("HttpStatusCodeForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorize to access this resource..
        /// </summary>
        public static string HttpStatusCodeUnauthorized {
            get {
                return ResourceManager.GetString("HttpStatusCodeUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occured during server communication.
        /// </summary>
        public static string HttpStatusCodeUnknown {
            get {
                return ResourceManager.GetString("HttpStatusCodeUnknown", resourceCulture);
            }
        }
    }
}
